language: ruby
cache: bundler

rvm:
  - 2.4.1

script: bundle exec rspec spec

addons:
  postgresql: "9.6.4"

before_script:
  - cp config/database.yml.travis config/database.yml
  - RAILS_ENV=test rake db:create
  - RAILS_ENV=test rake db:migrate
