language: ruby

rvm:
  - 2.4.1

script: bundle exec rspec spec

addons:
  postgresql: "9.6.4"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
