# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a68767c84cb3bf75e0c2424abda28d9a35ea8c06bee8d92f1349f29bf9ae0f681f35dc3cbd70560b69320e74db7c757cf85d95be96f058fc12ed862a59d1f7a9

test:
  secret_key_base: a952af045d33cf15a890c505f7c339607eb7802f83b5a1bbb6b62d056b40e44e860d202939cb2a9021aadfe679e250e6fdb95a2f78e946b51cca11e1a7d2e0d8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
